version: "3"
services:
  postgres:
    image: postgres:12.2-alpine
    container_name: postgres
    environment:
      POSTGRES_HOST_AUTH_METHOD: "trust"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./tmp/postgresql:/var/run/postgresql/
    ports:
      - "5432:5432"

volumes:
  postgres_data: